// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NoSqlU.Data;

#nullable disable

namespace Data.Migrations
{
    [DbContext(typeof(NoSqlUContext))]
    [Migration("20260924071321_AgregandoUsuarios")]
    partial class AgregandoUsuarios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NoSqlU.Data.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("categorias", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Cursos relacionados con frontend, backend y aplicaciones web.",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Desarrollo Web"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Cursos sobre SQL, NoSQL, modelado y administración de datos.",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Bases de Datos"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Cursos de diseño gráfico, UX/UI y herramientas creativas.",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Diseño Digital"
                        },
                        new
                        {
                            Id = 4,
                            Descripcion = "Cursos sobre emprendimiento, administración y marketing.",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Negocios"
                        },
                        new
                        {
                            Id = 5,
                            Descripcion = "Cursos de seguridad informática, redes y protección de sistemas.",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Ciberseguridad"
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Curso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int")
                        .HasColumnName("id_categoria");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("descripcion");

                    b.Property<long>("DuracionMinutos")
                        .HasColumnType("bigint")
                        .HasColumnName("duracion_minutos");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<DateTime>("FechaPublicacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_publicacion");

                    b.Property<int>("InstructorId")
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    b.Property<int>("NivelId")
                        .HasColumnType("int")
                        .HasColumnName("id_nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("precio");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("InstructorId");

                    b.HasIndex("NivelId");

                    b.ToTable("cursos", null, t =>
                        {
                            t.HasCheckConstraint("chk_cursos_duracion", "duracion_minutos > 0");

                            t.HasCheckConstraint("chk_cursos_precio", "precio > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaId = 1,
                            Descripcion = "Curso introductorio para crear páginas web modernas.",
                            DuracionMinutos = 300L,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPublicacion = new DateTime(2026, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            NivelId = 1,
                            Nombre = "HTML, CSS y JavaScript desde cero",
                            Precio = 499.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoriaId = 1,
                            Descripcion = "Aprende a crear sistemas web usando PHP y bases de datos MySQL.",
                            DuracionMinutos = 420L,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPublicacion = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            NivelId = 2,
                            Nombre = "PHP y MySQL para aplicaciones web",
                            Precio = 799.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoriaId = 2,
                            Descripcion = "Curso básico para aprender consultas, tablas, relaciones y filtros en SQL.",
                            DuracionMinutos = 240L,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPublicacion = new DateTime(2026, 5, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 3,
                            NivelId = 1,
                            Nombre = "Fundamentos de SQL",
                            Precio = 399.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoriaId = 2,
                            Descripcion = "Aprende documentos, colecciones, filtros y modelado NoSQL.",
                            DuracionMinutos = 360L,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPublicacion = new DateTime(2026, 5, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 4,
                            NivelId = 2,
                            Nombre = "MongoDB para principiantes",
                            Precio = 599.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoriaId = 3,
                            Descripcion = "Diseña interfaces atractivas y fáciles de usar.",
                            DuracionMinutos = 390L,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPublicacion = new DateTime(2026, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 1,
                            NivelId = 2,
                            Nombre = "UX/UI para interfaces modernas",
                            Precio = 699.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoriaId = 5,
                            Descripcion = "Introducción a amenazas, contraseñas, redes y buenas prácticas de seguridad.",
                            DuracionMinutos = 330L,
                            Estatus = "inactivo",
                            FechaCreacion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FechaPublicacion = new DateTime(2026, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            InstructorId = 2,
                            NivelId = 1,
                            Nombre = "Ciberseguridad básica",
                            Precio = 549.00m
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.CursoUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario_curso");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CursoId")
                        .HasColumnType("int")
                        .HasColumnName("id_curso");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("EN CURSO")
                        .HasColumnName("estatus");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_finalizacion");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inicio");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("CursoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("cursos_usuarios", (string)null);
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.DireccionUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_direccion");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Calle")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("calle");

                    b.Property<string>("CodigoPostal")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("codigo_postal");

                    b.Property<string>("Colonia")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("colonia");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    b.Property<string>("Municipio")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("municipio");

                    b.Property<string>("NumeroExterior")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_exterior");

                    b.Property<string>("NumeroInterior")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("numero_interior");

                    b.Property<string>("SexoId")
                        .HasColumnType("char(1)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.HasIndex("SexoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("direcciones_usuario", (string)null);
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Estado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_estado");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("NombreEstado")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombre_estado");

                    b.HasKey("Id");

                    b.ToTable("cat_estados", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            NombreEstado = "Aguascalientes"
                        },
                        new
                        {
                            Id = 2,
                            NombreEstado = "Baja California"
                        },
                        new
                        {
                            Id = 3,
                            NombreEstado = "Baja California Sur"
                        },
                        new
                        {
                            Id = 4,
                            NombreEstado = "Campeche"
                        },
                        new
                        {
                            Id = 5,
                            NombreEstado = "Coahuila de Zaragoza"
                        },
                        new
                        {
                            Id = 6,
                            NombreEstado = "Colima"
                        },
                        new
                        {
                            Id = 7,
                            NombreEstado = "Chiapas"
                        },
                        new
                        {
                            Id = 8,
                            NombreEstado = "Chihuahua"
                        },
                        new
                        {
                            Id = 9,
                            NombreEstado = "Ciudad de México"
                        },
                        new
                        {
                            Id = 10,
                            NombreEstado = "Durango"
                        },
                        new
                        {
                            Id = 11,
                            NombreEstado = "Guanajuato"
                        },
                        new
                        {
                            Id = 12,
                            NombreEstado = "Guerrero"
                        },
                        new
                        {
                            Id = 13,
                            NombreEstado = "Hidalgo"
                        },
                        new
                        {
                            Id = 14,
                            NombreEstado = "Jalisco"
                        },
                        new
                        {
                            Id = 15,
                            NombreEstado = "Estado de México"
                        },
                        new
                        {
                            Id = 16,
                            NombreEstado = "Michoacán de Ocampo"
                        },
                        new
                        {
                            Id = 17,
                            NombreEstado = "Morelos"
                        },
                        new
                        {
                            Id = 18,
                            NombreEstado = "Nayarit"
                        },
                        new
                        {
                            Id = 19,
                            NombreEstado = "Nuevo León"
                        },
                        new
                        {
                            Id = 20,
                            NombreEstado = "Oaxaca"
                        },
                        new
                        {
                            Id = 21,
                            NombreEstado = "Puebla"
                        },
                        new
                        {
                            Id = 22,
                            NombreEstado = "Querétaro"
                        },
                        new
                        {
                            Id = 23,
                            NombreEstado = "Quintana Roo"
                        },
                        new
                        {
                            Id = 24,
                            NombreEstado = "San Luis Potosí"
                        },
                        new
                        {
                            Id = 25,
                            NombreEstado = "Sinaloa"
                        },
                        new
                        {
                            Id = 26,
                            NombreEstado = "Sonora"
                        },
                        new
                        {
                            Id = 27,
                            NombreEstado = "Tabasco"
                        },
                        new
                        {
                            Id = 28,
                            NombreEstado = "Tamaulipas"
                        },
                        new
                        {
                            Id = 29,
                            NombreEstado = "Tlaxcala"
                        },
                        new
                        {
                            Id = 30,
                            NombreEstado = "Veracruz"
                        },
                        new
                        {
                            Id = 31,
                            NombreEstado = "Yucatán"
                        },
                        new
                        {
                            Id = 32,
                            NombreEstado = "Zacatecas"
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_instructor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasDefaultValue("")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasDefaultValue("")
                        .HasColumnName("email");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("instructores", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "laura.mendoza@email.com",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Laura Mendoza"
                        },
                        new
                        {
                            Id = 2,
                            Email = "carlos.ramirez@email.com",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Carlos Ramírez"
                        },
                        new
                        {
                            Id = 3,
                            Email = "andrea.torres@email.com",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Andrea Torres"
                        },
                        new
                        {
                            Id = 4,
                            Email = "miguel.hernandez@email.com",
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Miguel Hernández"
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_nivel");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_creacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("niveles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Básico"
                        },
                        new
                        {
                            Id = 2,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Intermedio"
                        },
                        new
                        {
                            Id = 3,
                            Estatus = "activo",
                            FechaCreacion = new DateTime(2026, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Avanzado"
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Sexo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(1)")
                        .HasColumnName("id_sexo");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estatus");

                    b.HasKey("Id");

                    b.ToTable("cat_sexo", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "M",
                            Descripcion = "Masculino",
                            Estatus = "ACTIVO"
                        },
                        new
                        {
                            Id = "F",
                            Descripcion = "Femenino",
                            Estatus = "ACTIVO"
                        },
                        new
                        {
                            Id = "X",
                            Descripcion = "No binario / Otro",
                            Estatus = "ACTIVO"
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApellidoMaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido_materno");

                    b.Property<string>("ApellidoPaterno")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("apellido_paterno");

                    b.Property<string>("CorreoEmpresarial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("correo_empresarial");

                    b.Property<int?>("EstadoId")
                        .HasColumnType("int");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("ACTIVO")
                        .HasColumnName("estatus");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("date")
                        .HasColumnName("fecha_inscripcion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("date")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<DateTime>("FechaRegistro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("fecha_registro")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("SexoId")
                        .IsRequired()
                        .HasColumnType("char(1)")
                        .HasColumnName("id_sexo");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("CorreoEmpresarial")
                        .IsUnique();

                    b.HasIndex("EstadoId");

                    b.HasIndex("SexoId");

                    b.ToTable("usuarios", null, t =>
                        {
                            t.HasCheckConstraint("chk_apellidos", "apellido_paterno IS NOT NULL OR apellido_materno IS NOT NULL");
                        });
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.UsuarioContrasena", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("id_usuario");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("UsuarioLogin")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("usuario");

                    b.HasKey("UsuarioId");

                    b.HasIndex("UsuarioLogin")
                        .IsUnique();

                    b.ToTable("usuario_contrasena", (string)null);
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Curso", b =>
                {
                    b.HasOne("NoSqlU.Data.Entities.Categoria", "Categoria")
                        .WithMany("Cursos")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_categoria");

                    b.HasOne("NoSqlU.Data.Entities.Instructor", "Instructor")
                        .WithMany("Cursos")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_instructor");

                    b.HasOne("NoSqlU.Data.Entities.Nivel", "Nivel")
                        .WithMany("Cursos")
                        .HasForeignKey("NivelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_nivel");

                    b.Navigation("Categoria");

                    b.Navigation("Instructor");

                    b.Navigation("Nivel");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.CursoUsuario", b =>
                {
                    b.HasOne("NoSqlU.Data.Entities.Curso", "Curso")
                        .WithMany()
                        .HasForeignKey("CursoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_usuarios_curso");

                    b.HasOne("NoSqlU.Data.Entities.Usuario", "Usuario")
                        .WithMany("CursosUsuarios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cursos_usuarios_usuario");

                    b.Navigation("Curso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.DireccionUsuario", b =>
                {
                    b.HasOne("NoSqlU.Data.Entities.Estado", "Estado")
                        .WithMany()
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_direccion_estado");

                    b.HasOne("NoSqlU.Data.Entities.Sexo", null)
                        .WithMany("Direcciones")
                        .HasForeignKey("SexoId");

                    b.HasOne("NoSqlU.Data.Entities.Usuario", "Usuario")
                        .WithMany("Direcciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_direccion_usuario");

                    b.Navigation("Estado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Usuario", b =>
                {
                    b.HasOne("NoSqlU.Data.Entities.Estado", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("EstadoId");

                    b.HasOne("NoSqlU.Data.Entities.Sexo", "Sexo")
                        .WithMany()
                        .HasForeignKey("SexoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuarios_sexo");

                    b.Navigation("Sexo");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.UsuarioContrasena", b =>
                {
                    b.HasOne("NoSqlU.Data.Entities.Usuario", "Usuario")
                        .WithOne("Contrasena")
                        .HasForeignKey("NoSqlU.Data.Entities.UsuarioContrasena", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_contrasena");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Categoria", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Estado", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Instructor", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Nivel", b =>
                {
                    b.Navigation("Cursos");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Sexo", b =>
                {
                    b.Navigation("Direcciones");
                });

            modelBuilder.Entity("NoSqlU.Data.Entities.Usuario", b =>
                {
                    b.Navigation("Contrasena");

                    b.Navigation("CursosUsuarios");

                    b.Navigation("Direcciones");
                });
#pragma warning restore 612, 618
        }
    }
}
